# Generated by Django 4.0.1 on 2022-01-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
    ]
